# Generated by Django 5.0.6 on 2024-09-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_agent_alter_packages_image_alter_packages_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
