# Generated by Django 5.0.6 on 2024-09-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bookinghistory',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
