# Generated by Django 5.0.6 on 2024-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_agent_bookinghistory_agent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
