# Generated by Django 5.0.6 on 2024-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
