# Generated by Django 5.0.6 on 2024-09-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_packages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
