# Generated by Django 5.0.6 on 2024-09-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_agent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='itineraries',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
