# Generated by Django 5.0.6 on 2024-09-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_packages_itineraries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
