# Generated by Django 5.0.6 on 2024-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_remove_agent_address_remove_agent_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
