# Generated by Django 5.0.6 on 2024-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
