# Generated by Django 5.0.6 on 2024-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_alter_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
